name: main-site
region: sfo
static_sites:
- name: main-website
  git:
    branch: prod
    repo_clone_url: https://github.com/bryce-evans/main-website.git
  source_dir: /
  output_dir: /
  build_command: git submodule update --init --recursive