name: main-website
region: sfo3

static_sites:
  - name: main-website
    github:
      repo: bryce-evans/main-website
      branch: prod
      deploy_on_push: true
      clone_submodules: true

    source_dir: /
    output_dir: /

    index_document: index.html
    error_document: 404.html

    routes:
      - path: /

    envs: []