name: main-website
region: sfo

static_sites:
  - name: web
    github:
      branch: master
      deploy_on_push: true

    # No build needed - serve files as-is
    source_dir: /
    output_dir: /

    # Enable git submodules (required for webgl-portals)
    git:
      submodules: true

    # Index and error documents
    index_document: index.html
    error_document: 404.html

    # Route configuration
    routes:
      - path: /

    # Environment variables (none needed for this static site)
    envs: []
